# Goeduhub Technologies - ML Training - Task 4
## Registration ID: GO_STP_939 
## Name: Manoj Kannan D

### 1.Import the numpy package under the name np and Print the numpy version and the configuration 

In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


### 2.Create a null vector of size 10

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3.Create Simple 1-D array and check type and check data types in array

In [3]:
sample = np.array([1,2,3,4,5])
print('Type:',type(sample))
print('Elements Type:',sample.dtype)

Type: <class 'numpy.ndarray'>
Elements Type: int32


### 4.How to find number of dimensions, bytes per element and bytes of memory used?

In [4]:
sample = np.array([1,2,3,4,5])
print('Dimensions:',sample.ndim)
print('Bytes per element:',sample.itemsize)
print('Memory occupies:',sample.itemsize*sample.size)

Dimensions: 1
Bytes per element: 4
Memory occupies: 20


### 5.Create a null vector of size 10 but the fifth value which is 1

In [5]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 6.Create a vector with values ranging from 10 to 49

In [6]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 7.Reverse a vector (first element becomes last)

In [7]:
arr = np.array([1,2,3,4,5])
print('Before reversing:',arr)
print('After reversing:',arr[::-1])

Before reversing: [1 2 3 4 5]
After reversing: [5 4 3 2 1]


### 8.Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 9.Find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)


### 10.Create a 3x3 identity matrix

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 11.Create a 3x3x3 array with random values

In [11]:
np.random.random((3,3,3))

array([[[0.29443949, 0.37203665, 0.38523268],
        [0.41700781, 0.89640912, 0.38907617],
        [0.92121112, 0.38914808, 0.16830543]],

       [[0.21263308, 0.79648022, 0.12052714],
        [0.22135163, 0.16457459, 0.15928236],
        [0.04985032, 0.14791135, 0.71571116]],

       [[0.9617453 , 0.59299098, 0.91032351],
        [0.21002467, 0.62079436, 0.09802175],
        [0.63780107, 0.01944482, 0.1250219 ]]])

### 12.Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
arr = np.random.random((10,10))
print("Minimum Value :", np.min(arr))
print("Maximum Value :", np.max(arr))

Minimum Value : 0.004555717568630491
Maximum Value : 0.9971948458460347


### 13.Create a random vector of size 30 and find the mean value

In [13]:
arr = np.random.random((6,5))
print('Mean:',np.mean(arr))

Mean: 0.4910541704418773


### 14.Create a 2d array with 1 on the border and 0 inside

In [14]:
arr = np.zeros((3,3))
pad = np.pad(arr, pad_width = 1, constant_values = 1)
# np.pad - Pad an array of elements
print(pad)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 15.How to add a border (filled with 0's) around an existing array? 

In [15]:
arr = np.random.randint(low=1,high=10,size=(3,3))
pad = np.pad(arr, pad_width = 1, constant_values = 0)
print(pad)

[[0 0 0 0 0]
 [0 2 9 1 0]
 [0 8 3 4 0]
 [0 9 8 8 0]
 [0 0 0 0 0]]


### 16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?
#### Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]
#### Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [16]:
arr = np.array([[ 1, 2, 3, 4, 5, 6, 7],
                  [ 8, 9, 10, 11, 12, 13, 14]])
print('arr[1][5] =',arr[1][5])
print('First Row:',arr[0])
print('Third Column:',arr[:,2])
print(arr[0,1:7:2])
arr[1,5] = 20
print(arr)

arr[1][5] = 13
First Row: [1 2 3 4 5 6 7]
Third Column: [ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### 17.How to Convert a 1D array to a 2D array with 2 rows

In [17]:
arr1D = np.ones((4))
arr2D = arr1D.reshape(2,2)
print(arr1D)
print(arr2D)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


### 18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#### Input: a = np.array([1,2,3])
#### Desired Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [18]:
a = np.array([1,2,3])
pattern = np.append(np.repeat(a,3),np.tile(a,3))
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### 19.Write a program to show how Numpy taking less memory compared to Python List?

In [19]:
import sys
l = [11,22,33,44,55,66,77,88,99]
a = np.array([11,22,33,44,55,66,77,88,99])
print('Memory used by list items:',sys.getsizeof(l))
print('Memory used by array items:',a.itemsize*a.size)
print('Thus, Numpy array consumes less memory.')

Memory used by list items: 128
Memory used by array items: 36
Thus, Numpy array consumes less memory.


### 20.Write a program to show how Numpy taking less time compared to Python List?

In [20]:
import datetime

l1 = range(1000000)
l2 = range(1000000)

a1 = np.arange(1000000)
a2 = np.arange(1000000)

tic = datetime.datetime.now() 
for i in range(1000000):
    list_product = l1[i]*l2[i]
toc = datetime.datetime.now()  
print('Time consumed by list:',toc-tic)

tic = datetime.datetime.now() 
array_product = a1*a2
toc = datetime.datetime.now()  

print('Time consumed by array:',toc-tic)

Time consumed by list: 0:00:00.300197
Time consumed by array: 0:00:00.002992
